on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  merge_group:

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Upload website
        uses: actions/upload-artifact@v7
        if: github.event_name == 'pull_request'
        with:
          name: site
          retention-days: 5
          path: _site

      - name: Deploy to GitHub pages 🚀
        if: github.ref_name == 'main'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
          clean: true
